dist : trusty
language: java
jdk:
  - oraclejdk8
  - oraclejdk9
  - oraclejdk10
sudo: required
env:  
  global:
    - MAVEN_SETTINGS="${TRAVIS_BUILD_DIR}/gsi-config"
    - MAVEN_OPTS="-Xms1g -Xmx2g" 

git:
  depth: 3

before_install:
    - git clone https://github.com/oicr-gsi/gsi-config.git "${MAVEN_SETTINGS}"
    - cp "${MAVEN_SETTINGS}/settings.xml" "${HOME}/.m2/settings.xml"

before_script:
  - export MAVEN_OPTS='-Xms1g -Xmx2g'

script: ./.travis-build.sh

cache:
  directories:
    - "$HOME/.m2"
