dist: trusty
language: java
jdk:
  - oraclejdk8
  - oraclejdk9
sudo: required
install: true
env:
  global:
    - MAVEN_SETTINGS="${TRAVIS_BUILD_DIR}/gsi-config"
    - MAVEN_OPTS="-Xms1g -Xmx2g"
matrix:
  include:
    - jdk: openjdk11
      before_install:
        - sudo apt-get -y install build-essential pkg-config libjsoncpp-dev
        - rm "${JAVA_HOME}/lib/security/cacerts"
        - ln -s /etc/ssl/certs/java/cacerts "${JAVA_HOME}/lib/security/cacerts"

git:
  depth: 3

before_install:
    - sudo apt-get -y install build-essential pkg-config libjsoncpp-dev
    - git clone https://github.com/oicr-gsi/gsi-config.git "${MAVEN_SETTINGS}"
    - cp "${MAVEN_SETTINGS}/settings.xml" "${HOME}/.m2/settings.xml"

before_script:
  - export MAVEN_OPTS='-Xms1g -Xmx2g'

script: ./.travis-build.sh

cache:
  directories:
    - "$HOME/.m2"
    - "$HOME/.sonar/cache"
addons:
  sonarcloud:
    organization: "oicr-gsi"
    token:
      secure: "Wp9xElIJStdsCvgbIxXGUK80P54PYGrD0Jmym8yE/dupHkoRdum7SJZoQkZYpHxU6j0QLvU0EBuWjvSmXwBA8s0VEqDIhF9jkjELYph2EcY/lTRxkoh4wIw2Tc/1GVfd2Pymeyqb8s5EwoHqm4AFr9twb/TfbQFk0L4P4gr6soB24qFKBE+B6uk2Fvz0U28qTwL3jHIxWDSoZi6bfcbgjAAkR654izTt6Q07vSWZDUWiKbiteEkYaYmWldbcZXNut3/hjT1x1llyVLTxzUHvoeed+34yhZg4bTc/ix5RhSGGAUymQOtDK0x3ujJKOwwFsMJ/82WhYbWdxwWzjIa3j6/ROGFvnSzfQYG3XmWjuRlaGyT96ZQhU2dtpmbIfyOHWdBeG+JcnfAmQx5KppodY25j8Zls2tuvExGOwMsBk7rjzN0tyVPBpXRfIbH3UMjliZ1/IxB+RYQ6BInqxqoc3P7qhl6F8yVB3XL4iPYJkwBbVqgEWTOTZq43Q7OaZPx+cYmJblwMTGlFCGvHoYf8fSYEHeTAtyWKwputp2UvESJCRJvDtO3cqAXjv1m8tq4xqZCl34uU5EJ4nPhWvTDY7tm9iybTCgg35xHShrHBxnhfjBR5CQl2bFtbeUfsJTqs6EesaSgXedQzUE9W0WIC6V/gwhNwgbaCwjZSgPp3b58="

