theme: jekyll-theme-slate
base_url: /shesmu
source: ./docs
plugins:
  - jekyll-relative-links
markdown: kramdown
kramdown:
  parse_block_html: true
relative_links:
  enabled:     true
  collections: false
