#!/bin/sh
export CLASSPATH=/usr/share/shesmu/*
IFS=":"
export SHESMU_DATA="$*"

exec java -Djava.security.egd=file:/dev/./urandom -agentlib:jdwp=transport=dt_socket,server=y,address=7000,suspend=n -XX:+UseG1GC -XX:+UseStringDeduplication -XX:+AlwaysPreTouch -Xms${MEMORY:-13g} -Xmx${MEMORY:-13g} ca.on.oicr.gsi.shesmu.Server
