// This file will be generated by plugins on the Shemu server
import { UIElement } from "./html.js";
import { Action } from "./action.js";
declare module "actions" {
  export const actionRender: Map<string, (a: Action) => UIElement>;
}
