/*
 * Cromwell Server REST API
 * Describes the REST API provided by a Cromwell server
 *
 * OpenAPI spec version: 30
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package ca.on.oicr.gsi.shesmu.cromwell;

import java.time.OffsetDateTime;

/** Result for an individual workflow returned by a workflow query */
public class WorkflowQueryResult {
  private OffsetDateTime end = null;
  private String id = null;
  private String name = null;
  private OffsetDateTime start = null;
  private String status = null;
  private OffsetDateTime submission = null;

  public OffsetDateTime getEnd() {
    return end;
  }

  public String getId() {
    return id;
  }

  public String getName() {
    return name;
  }

  public OffsetDateTime getStart() {
    return start;
  }

  public String getStatus() {
    return status;
  }

  public OffsetDateTime getSubmission() {
    return submission;
  }

  public void setEnd(OffsetDateTime end) {
    this.end = end;
  }

  public void setId(String id) {
    this.id = id;
  }

  public void setName(String name) {
    this.name = name;
  }

  public void setStart(OffsetDateTime start) {
    this.start = start;
  }

  public void setStatus(String status) {
    this.status = status;
  }

  public void setSubmission(OffsetDateTime submission) {
    this.submission = submission;
  }
}
