/*
 * Cromwell Server REST API
 * Describes the REST API provided by a Cromwell server
 *
 * OpenAPI spec version: 30
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package ca.on.oicr.gsi.shesmu.cromwell;

import java.util.ArrayList;
import java.util.List;

/** Response to a workflow query */
public class WorkflowQueryResponse {
  private List<WorkflowQueryResult> results = new ArrayList<>();
  private Integer totalResultsCount = null;

  public List<WorkflowQueryResult> getResults() {
    return results;
  }

  public Integer getTotalResultsCount() {
    return totalResultsCount;
  }

  public void setResults(List<WorkflowQueryResult> results) {
    this.results = results;
  }

  public void setTotalResultsCount(Integer totalResultsCount) {
    this.totalResultsCount = totalResultsCount;
  }
}
