/*
 * Cromwell Server REST API
 * Describes the REST API provided by a Cromwell server
 *
 * OpenAPI spec version: 30
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package ca.on.oicr.gsi.shesmu.cromwell;

/** WorkflowIdAndStatus */
public class WorkflowIdAndStatus {

  private String id = null;
  private String status = null;

  public String getId() {
    return id;
  }

  public String getStatus() {
    return status;
  }

  public void setId(String id) {
    this.id = id;
  }

  public void setStatus(String status) {
    this.status = status;
  }
}
