package ca.on.oicr.gsi.shesmu.runtime;

import static java.lang.annotation.ElementType.FIELD;
import static java.lang.annotation.ElementType.METHOD;
import static java.lang.annotation.RetentionPolicy.SOURCE;

import java.lang.annotation.Retention;
import java.lang.annotation.Target;

/**
 * This method is called by code generated by the Shesmu compiler.
 *
 * It should not be considered unused and any changes to it must be matched by
 * changes in the code generator.
 */
@Retention(SOURCE)
@Target({ METHOD, FIELD })
public @interface RuntimeInterop {

}
