PREFIX=/usr

install:
	install -d -m 755 $(DESTDIR)$(PREFIX)/share/vim/registry
	install -m 755 vim-syntax-shesmu.yaml $(DESTDIR)$(PREFIX)/share/vim/registry/vim-syntax-shesmu.yaml
	install -d -m 755 $(DESTDIR)$(PREFIX)/share/vim/addons/ftdetect
	install -m 644 ftdetect.vim $(DESTDIR)$(PREFIX)/share/vim/addons/ftdetect/shesmu.vim; done
	install -d -m 755 $(DESTDIR)$(PREFIX)/share/vim/addons/syntax
	install -m 644 syntax.vim $(DESTDIR)$(PREFIX)/share/vim/addons/syntax/shesmu.vim; done
