/*
 * Cromwell Server REST API
 * Describes the REST API provided by a Cromwell server
 *
 * OpenAPI spec version: 30
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/** BackendResponse */
@javax.annotation.Generated(
    value = "io.swagger.codegen.languages.JavaClientCodegen",
    date = "2018-12-03T20:33:09.260Z")
public class BackendResponse {
  @SerializedName("supportedBackends")
  private List<String> supportedBackends = new ArrayList<String>();

  @SerializedName("defaultBackend")
  private String defaultBackend = null;

  public BackendResponse supportedBackends(List<String> supportedBackends) {
    this.supportedBackends = supportedBackends;
    return this;
  }

  public BackendResponse addSupportedBackendsItem(String supportedBackendsItem) {
    this.supportedBackends.add(supportedBackendsItem);
    return this;
  }

  /**
   * The backends supported by this server
   *
   * @return supportedBackends
   */
  @ApiModelProperty(required = true, value = "The backends supported by this server")
  public List<String> getSupportedBackends() {
    return supportedBackends;
  }

  public void setSupportedBackends(List<String> supportedBackends) {
    this.supportedBackends = supportedBackends;
  }

  public BackendResponse defaultBackend(String defaultBackend) {
    this.defaultBackend = defaultBackend;
    return this;
  }

  /**
   * The default backend of this server
   *
   * @return defaultBackend
   */
  @ApiModelProperty(required = true, value = "The default backend of this server")
  public String getDefaultBackend() {
    return defaultBackend;
  }

  public void setDefaultBackend(String defaultBackend) {
    this.defaultBackend = defaultBackend;
  }

  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BackendResponse backendResponse = (BackendResponse) o;
    return Objects.equals(this.supportedBackends, backendResponse.supportedBackends)
        && Objects.equals(this.defaultBackend, backendResponse.defaultBackend);
  }

  @Override
  public int hashCode() {
    return Objects.hash(supportedBackends, defaultBackend);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BackendResponse {\n");

    sb.append("    supportedBackends: ").append(toIndentedString(supportedBackends)).append("\n");
    sb.append("    defaultBackend: ").append(toIndentedString(defaultBackend)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
