/*
 * Cromwell Server REST API
 * Describes the REST API provided by a Cromwell server
 *
 * OpenAPI spec version: 30
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.Objects;
import org.threeten.bp.OffsetDateTime;

/** Call level metadata */
@ApiModel(description = "Call level metadata")
@javax.annotation.Generated(
    value = "io.swagger.codegen.languages.JavaClientCodegen",
    date = "2018-12-03T20:33:09.260Z")
public class CallMetadata {
  @SerializedName("inputs")
  private Object inputs = null;

  @SerializedName("executionStatus")
  private String executionStatus = null;

  @SerializedName("backend")
  private String backend = null;

  @SerializedName("backendStatus")
  private String backendStatus = null;

  @SerializedName("start")
  private OffsetDateTime start = null;

  @SerializedName("end")
  private OffsetDateTime end = null;

  @SerializedName("jobId")
  private String jobId = null;

  @SerializedName("failures")
  private FailureMessage failures = null;

  @SerializedName("returnCode")
  private Integer returnCode = null;

  @SerializedName("stdout")
  private String stdout = null;

  @SerializedName("stderr")
  private String stderr = null;

  @SerializedName("backendLogs")
  private Object backendLogs = null;

  public CallMetadata inputs(Object inputs) {
    this.inputs = inputs;
    return this;
  }

  /**
   * Mapping of input fully qualified names to stringified values
   *
   * @return inputs
   */
  @ApiModelProperty(
      required = true,
      value = "Mapping of input fully qualified names to stringified values")
  public Object getInputs() {
    return inputs;
  }

  public void setInputs(Object inputs) {
    this.inputs = inputs;
  }

  public CallMetadata executionStatus(String executionStatus) {
    this.executionStatus = executionStatus;
    return this;
  }

  /**
   * Status in Cromwell execution terms.
   *
   * @return executionStatus
   */
  @ApiModelProperty(required = true, value = "Status in Cromwell execution terms.")
  public String getExecutionStatus() {
    return executionStatus;
  }

  public void setExecutionStatus(String executionStatus) {
    this.executionStatus = executionStatus;
  }

  public CallMetadata backend(String backend) {
    this.backend = backend;
    return this;
  }

  /**
   * The type of backend on which the call executed (e.g. JES, SGE, Local)
   *
   * @return backend
   */
  @ApiModelProperty(value = "The type of backend on which the call executed (e.g. JES, SGE, Local)")
  public String getBackend() {
    return backend;
  }

  public void setBackend(String backend) {
    this.backend = backend;
  }

  public CallMetadata backendStatus(String backendStatus) {
    this.backendStatus = backendStatus;
    return this;
  }

  /**
   * Status in backend-specific terms. Currently this will only be defined for the JES backend.
   *
   * @return backendStatus
   */
  @ApiModelProperty(
      value =
          "Status in backend-specific terms.  Currently this will only be defined for the JES backend.")
  public String getBackendStatus() {
    return backendStatus;
  }

  public void setBackendStatus(String backendStatus) {
    this.backendStatus = backendStatus;
  }

  public CallMetadata start(OffsetDateTime start) {
    this.start = start;
    return this;
  }

  /**
   * Start datetime of the call execution in ISO8601 format with milliseconds
   *
   * @return start
   */
  @ApiModelProperty(
      value = "Start datetime of the call execution in ISO8601 format with milliseconds")
  public OffsetDateTime getStart() {
    return start;
  }

  public void setStart(OffsetDateTime start) {
    this.start = start;
  }

  public CallMetadata end(OffsetDateTime end) {
    this.end = end;
    return this;
  }

  /**
   * End datetime of the call execution in ISO8601 format with milliseconds
   *
   * @return end
   */
  @ApiModelProperty(
      value = "End datetime of the call execution in ISO8601 format with milliseconds")
  public OffsetDateTime getEnd() {
    return end;
  }

  public void setEnd(OffsetDateTime end) {
    this.end = end;
  }

  public CallMetadata jobId(String jobId) {
    this.jobId = jobId;
    return this;
  }

  /**
   * Backend-specific job ID
   *
   * @return jobId
   */
  @ApiModelProperty(value = "Backend-specific job ID")
  public String getJobId() {
    return jobId;
  }

  public void setJobId(String jobId) {
    this.jobId = jobId;
  }

  public CallMetadata failures(FailureMessage failures) {
    this.failures = failures;
    return this;
  }

  /**
   * Get failures
   *
   * @return failures
   */
  @ApiModelProperty(value = "")
  public FailureMessage getFailures() {
    return failures;
  }

  public void setFailures(FailureMessage failures) {
    this.failures = failures;
  }

  public CallMetadata returnCode(Integer returnCode) {
    this.returnCode = returnCode;
    return this;
  }

  /**
   * Call execution return code
   *
   * @return returnCode
   */
  @ApiModelProperty(value = "Call execution return code")
  public Integer getReturnCode() {
    return returnCode;
  }

  public void setReturnCode(Integer returnCode) {
    this.returnCode = returnCode;
  }

  public CallMetadata stdout(String stdout) {
    this.stdout = stdout;
    return this;
  }

  /**
   * Path to the standard output file for this call
   *
   * @return stdout
   */
  @ApiModelProperty(value = "Path to the standard output file for this call")
  public String getStdout() {
    return stdout;
  }

  public void setStdout(String stdout) {
    this.stdout = stdout;
  }

  public CallMetadata stderr(String stderr) {
    this.stderr = stderr;
    return this;
  }

  /**
   * Path to the standard error file for this call
   *
   * @return stderr
   */
  @ApiModelProperty(value = "Path to the standard error file for this call")
  public String getStderr() {
    return stderr;
  }

  public void setStderr(String stderr) {
    this.stderr = stderr;
  }

  public CallMetadata backendLogs(Object backendLogs) {
    this.backendLogs = backendLogs;
    return this;
  }

  /**
   * Paths to backend specific logs for this call
   *
   * @return backendLogs
   */
  @ApiModelProperty(value = "Paths to backend specific logs for this call")
  public Object getBackendLogs() {
    return backendLogs;
  }

  public void setBackendLogs(Object backendLogs) {
    this.backendLogs = backendLogs;
  }

  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CallMetadata callMetadata = (CallMetadata) o;
    return Objects.equals(this.inputs, callMetadata.inputs)
        && Objects.equals(this.executionStatus, callMetadata.executionStatus)
        && Objects.equals(this.backend, callMetadata.backend)
        && Objects.equals(this.backendStatus, callMetadata.backendStatus)
        && Objects.equals(this.start, callMetadata.start)
        && Objects.equals(this.end, callMetadata.end)
        && Objects.equals(this.jobId, callMetadata.jobId)
        && Objects.equals(this.failures, callMetadata.failures)
        && Objects.equals(this.returnCode, callMetadata.returnCode)
        && Objects.equals(this.stdout, callMetadata.stdout)
        && Objects.equals(this.stderr, callMetadata.stderr)
        && Objects.equals(this.backendLogs, callMetadata.backendLogs);
  }

  @Override
  public int hashCode() {
    return Objects.hash(
        inputs,
        executionStatus,
        backend,
        backendStatus,
        start,
        end,
        jobId,
        failures,
        returnCode,
        stdout,
        stderr,
        backendLogs);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CallMetadata {\n");

    sb.append("    inputs: ").append(toIndentedString(inputs)).append("\n");
    sb.append("    executionStatus: ").append(toIndentedString(executionStatus)).append("\n");
    sb.append("    backend: ").append(toIndentedString(backend)).append("\n");
    sb.append("    backendStatus: ").append(toIndentedString(backendStatus)).append("\n");
    sb.append("    start: ").append(toIndentedString(start)).append("\n");
    sb.append("    end: ").append(toIndentedString(end)).append("\n");
    sb.append("    jobId: ").append(toIndentedString(jobId)).append("\n");
    sb.append("    failures: ").append(toIndentedString(failures)).append("\n");
    sb.append("    returnCode: ").append(toIndentedString(returnCode)).append("\n");
    sb.append("    stdout: ").append(toIndentedString(stdout)).append("\n");
    sb.append("    stderr: ").append(toIndentedString(stderr)).append("\n");
    sb.append("    backendLogs: ").append(toIndentedString(backendLogs)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
