/*
 * Cromwell Server REST API
 * Describes the REST API provided by a Cromwell server
 *
 * OpenAPI spec version: 30
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.Objects;
import org.threeten.bp.OffsetDateTime;

/** Failure messages */
@ApiModel(description = "Failure messages")
@javax.annotation.Generated(
    value = "io.swagger.codegen.languages.JavaClientCodegen",
    date = "2018-12-03T20:33:09.260Z")
public class FailureMessage {
  @SerializedName("failure")
  private String failure = null;

  @SerializedName("timestamp")
  private OffsetDateTime timestamp = null;

  public FailureMessage failure(String failure) {
    this.failure = failure;
    return this;
  }

  /**
   * The failure message
   *
   * @return failure
   */
  @ApiModelProperty(required = true, value = "The failure message")
  public String getFailure() {
    return failure;
  }

  public void setFailure(String failure) {
    this.failure = failure;
  }

  public FailureMessage timestamp(OffsetDateTime timestamp) {
    this.timestamp = timestamp;
    return this;
  }

  /**
   * The time at which this failure occurred
   *
   * @return timestamp
   */
  @ApiModelProperty(required = true, value = "The time at which this failure occurred")
  public OffsetDateTime getTimestamp() {
    return timestamp;
  }

  public void setTimestamp(OffsetDateTime timestamp) {
    this.timestamp = timestamp;
  }

  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FailureMessage failureMessage = (FailureMessage) o;
    return Objects.equals(this.failure, failureMessage.failure)
        && Objects.equals(this.timestamp, failureMessage.timestamp);
  }

  @Override
  public int hashCode() {
    return Objects.hash(failure, timestamp);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class FailureMessage {\n");

    sb.append("    failure: ").append(toIndentedString(failure)).append("\n");
    sb.append("    timestamp: ").append(toIndentedString(timestamp)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
