/*
 * Cromwell Server REST API
 * Describes the REST API provided by a Cromwell server
 *
 * OpenAPI spec version: 30
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.Objects;

/** Returns the version of Cromwell */
@ApiModel(description = "Returns the version of Cromwell")
@javax.annotation.Generated(
    value = "io.swagger.codegen.languages.JavaClientCodegen",
    date = "2018-12-03T20:33:09.260Z")
public class VersionResponse {
  @SerializedName("cromwell")
  private String cromwell = null;

  public VersionResponse cromwell(String cromwell) {
    this.cromwell = cromwell;
    return this;
  }

  /**
   * The version of the Cromwell Engine
   *
   * @return cromwell
   */
  @ApiModelProperty(example = "30", value = "The version of the Cromwell Engine")
  public String getCromwell() {
    return cromwell;
  }

  public void setCromwell(String cromwell) {
    this.cromwell = cromwell;
  }

  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    VersionResponse versionResponse = (VersionResponse) o;
    return Objects.equals(this.cromwell, versionResponse.cromwell);
  }

  @Override
  public int hashCode() {
    return Objects.hash(cromwell);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class VersionResponse {\n");

    sb.append("    cromwell: ").append(toIndentedString(cromwell)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
