/*
 * Cromwell Server REST API
 * Describes the REST API provided by a Cromwell server
 *
 * OpenAPI spec version: 30
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.Objects;
import org.threeten.bp.OffsetDateTime;

/** Workflow and call level metadata */
@ApiModel(description = "Workflow and call level metadata")
@javax.annotation.Generated(
    value = "io.swagger.codegen.languages.JavaClientCodegen",
    date = "2018-12-03T20:33:09.260Z")
public class WorkflowMetadataResponse {
  @SerializedName("id")
  private String id = null;

  @SerializedName("status")
  private String status = null;

  @SerializedName("submission")
  private OffsetDateTime submission = null;

  @SerializedName("start")
  private OffsetDateTime start = null;

  @SerializedName("end")
  private OffsetDateTime end = null;

  @SerializedName("inputs")
  private Object inputs = null;

  @SerializedName("outputs")
  private Object outputs = null;

  @SerializedName("calls")
  private CallMetadata calls = null;

  @SerializedName("failures")
  private FailureMessage failures = null;

  public WorkflowMetadataResponse id(String id) {
    this.id = id;
    return this;
  }

  /**
   * The identifier of the workflow
   *
   * @return id
   */
  @ApiModelProperty(required = true, value = "The identifier of the workflow")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public WorkflowMetadataResponse status(String status) {
    this.status = status;
    return this;
  }

  /**
   * The status of the workflow
   *
   * @return status
   */
  @ApiModelProperty(required = true, value = "The status of the workflow")
  public String getStatus() {
    return status;
  }

  public void setStatus(String status) {
    this.status = status;
  }

  public WorkflowMetadataResponse submission(OffsetDateTime submission) {
    this.submission = submission;
    return this;
  }

  /**
   * Submission datetime of the workflow in ISO8601 format with milliseconds
   *
   * @return submission
   */
  @ApiModelProperty(
      required = true,
      value = "Submission datetime of the workflow in ISO8601 format with milliseconds")
  public OffsetDateTime getSubmission() {
    return submission;
  }

  public void setSubmission(OffsetDateTime submission) {
    this.submission = submission;
  }

  public WorkflowMetadataResponse start(OffsetDateTime start) {
    this.start = start;
    return this;
  }

  /**
   * Start datetime of the workflow in ISO8601 format with milliseconds
   *
   * @return start
   */
  @ApiModelProperty(value = "Start datetime of the workflow in ISO8601 format with milliseconds")
  public OffsetDateTime getStart() {
    return start;
  }

  public void setStart(OffsetDateTime start) {
    this.start = start;
  }

  public WorkflowMetadataResponse end(OffsetDateTime end) {
    this.end = end;
    return this;
  }

  /**
   * End datetime of the workflow in ISO8601 format with milliseconds
   *
   * @return end
   */
  @ApiModelProperty(value = "End datetime of the workflow in ISO8601 format with milliseconds")
  public OffsetDateTime getEnd() {
    return end;
  }

  public void setEnd(OffsetDateTime end) {
    this.end = end;
  }

  public WorkflowMetadataResponse inputs(Object inputs) {
    this.inputs = inputs;
    return this;
  }

  /**
   * Map of input keys to input values
   *
   * @return inputs
   */
  @ApiModelProperty(value = "Map of input keys to input values")
  public Object getInputs() {
    return inputs;
  }

  public void setInputs(Object inputs) {
    this.inputs = inputs;
  }

  public WorkflowMetadataResponse outputs(Object outputs) {
    this.outputs = outputs;
    return this;
  }

  /**
   * Map of output keys to output values
   *
   * @return outputs
   */
  @ApiModelProperty(value = "Map of output keys to output values")
  public Object getOutputs() {
    return outputs;
  }

  public void setOutputs(Object outputs) {
    this.outputs = outputs;
  }

  public WorkflowMetadataResponse calls(CallMetadata calls) {
    this.calls = calls;
    return this;
  }

  /**
   * Get calls
   *
   * @return calls
   */
  @ApiModelProperty(value = "")
  public CallMetadata getCalls() {
    return calls;
  }

  public void setCalls(CallMetadata calls) {
    this.calls = calls;
  }

  public WorkflowMetadataResponse failures(FailureMessage failures) {
    this.failures = failures;
    return this;
  }

  /**
   * Get failures
   *
   * @return failures
   */
  @ApiModelProperty(value = "")
  public FailureMessage getFailures() {
    return failures;
  }

  public void setFailures(FailureMessage failures) {
    this.failures = failures;
  }

  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    WorkflowMetadataResponse workflowMetadataResponse = (WorkflowMetadataResponse) o;
    return Objects.equals(this.id, workflowMetadataResponse.id)
        && Objects.equals(this.status, workflowMetadataResponse.status)
        && Objects.equals(this.submission, workflowMetadataResponse.submission)
        && Objects.equals(this.start, workflowMetadataResponse.start)
        && Objects.equals(this.end, workflowMetadataResponse.end)
        && Objects.equals(this.inputs, workflowMetadataResponse.inputs)
        && Objects.equals(this.outputs, workflowMetadataResponse.outputs)
        && Objects.equals(this.calls, workflowMetadataResponse.calls)
        && Objects.equals(this.failures, workflowMetadataResponse.failures);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, status, submission, start, end, inputs, outputs, calls, failures);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class WorkflowMetadataResponse {\n");

    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    submission: ").append(toIndentedString(submission)).append("\n");
    sb.append("    start: ").append(toIndentedString(start)).append("\n");
    sb.append("    end: ").append(toIndentedString(end)).append("\n");
    sb.append("    inputs: ").append(toIndentedString(inputs)).append("\n");
    sb.append("    outputs: ").append(toIndentedString(outputs)).append("\n");
    sb.append("    calls: ").append(toIndentedString(calls)).append("\n");
    sb.append("    failures: ").append(toIndentedString(failures)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
