/*
 * Cromwell Server REST API
 * Describes the REST API provided by a Cromwell server
 *
 * OpenAPI spec version: 30
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/** Response to a workflow query */
@ApiModel(description = "Response to a workflow query")
@javax.annotation.Generated(
    value = "io.swagger.codegen.languages.JavaClientCodegen",
    date = "2018-12-03T20:33:09.260Z")
public class WorkflowQueryResponse {
  @SerializedName("results")
  private List<WorkflowQueryResult> results = new ArrayList<WorkflowQueryResult>();

  @SerializedName("totalResultsCount")
  private Integer totalResultsCount = null;

  public WorkflowQueryResponse results(List<WorkflowQueryResult> results) {
    this.results = results;
    return this;
  }

  public WorkflowQueryResponse addResultsItem(WorkflowQueryResult resultsItem) {
    this.results.add(resultsItem);
    return this;
  }

  /**
   * Get results
   *
   * @return results
   */
  @ApiModelProperty(required = true, value = "")
  public List<WorkflowQueryResult> getResults() {
    return results;
  }

  public void setResults(List<WorkflowQueryResult> results) {
    this.results = results;
  }

  public WorkflowQueryResponse totalResultsCount(Integer totalResultsCount) {
    this.totalResultsCount = totalResultsCount;
    return this;
  }

  /**
   * Get totalResultsCount
   *
   * @return totalResultsCount
   */
  @ApiModelProperty(required = true, value = "")
  public Integer getTotalResultsCount() {
    return totalResultsCount;
  }

  public void setTotalResultsCount(Integer totalResultsCount) {
    this.totalResultsCount = totalResultsCount;
  }

  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    WorkflowQueryResponse workflowQueryResponse = (WorkflowQueryResponse) o;
    return Objects.equals(this.results, workflowQueryResponse.results)
        && Objects.equals(this.totalResultsCount, workflowQueryResponse.totalResultsCount);
  }

  @Override
  public int hashCode() {
    return Objects.hash(results, totalResultsCount);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class WorkflowQueryResponse {\n");

    sb.append("    results: ").append(toIndentedString(results)).append("\n");
    sb.append("    totalResultsCount: ").append(toIndentedString(totalResultsCount)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
