/*
 * Cromwell Server REST API
 * Describes the REST API provided by a Cromwell server
 *
 * OpenAPI spec version: 30
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.Objects;
import org.threeten.bp.OffsetDateTime;

/** Result for an individual workflow returned by a workflow query */
@ApiModel(description = "Result for an individual workflow returned by a workflow query")
@javax.annotation.Generated(
    value = "io.swagger.codegen.languages.JavaClientCodegen",
    date = "2018-12-03T20:33:09.260Z")
public class WorkflowQueryResult {
  @SerializedName("id")
  private String id = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("status")
  private String status = null;

  @SerializedName("submission")
  private OffsetDateTime submission = null;

  @SerializedName("start")
  private OffsetDateTime start = null;

  @SerializedName("end")
  private OffsetDateTime end = null;

  public WorkflowQueryResult id(String id) {
    this.id = id;
    return this;
  }

  /**
   * Workflow ID
   *
   * @return id
   */
  @ApiModelProperty(required = true, value = "Workflow ID")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public WorkflowQueryResult name(String name) {
    this.name = name;
    return this;
  }

  /**
   * Workflow name
   *
   * @return name
   */
  @ApiModelProperty(required = true, value = "Workflow name")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public WorkflowQueryResult status(String status) {
    this.status = status;
    return this;
  }

  /**
   * Workflow status
   *
   * @return status
   */
  @ApiModelProperty(required = true, value = "Workflow status")
  public String getStatus() {
    return status;
  }

  public void setStatus(String status) {
    this.status = status;
  }

  public WorkflowQueryResult submission(OffsetDateTime submission) {
    this.submission = submission;
    return this;
  }

  /**
   * Workflow submission datetime
   *
   * @return submission
   */
  @ApiModelProperty(value = "Workflow submission datetime")
  public OffsetDateTime getSubmission() {
    return submission;
  }

  public void setSubmission(OffsetDateTime submission) {
    this.submission = submission;
  }

  public WorkflowQueryResult start(OffsetDateTime start) {
    this.start = start;
    return this;
  }

  /**
   * Workflow start datetime
   *
   * @return start
   */
  @ApiModelProperty(value = "Workflow start datetime")
  public OffsetDateTime getStart() {
    return start;
  }

  public void setStart(OffsetDateTime start) {
    this.start = start;
  }

  public WorkflowQueryResult end(OffsetDateTime end) {
    this.end = end;
    return this;
  }

  /**
   * Workflow end datetime
   *
   * @return end
   */
  @ApiModelProperty(value = "Workflow end datetime")
  public OffsetDateTime getEnd() {
    return end;
  }

  public void setEnd(OffsetDateTime end) {
    this.end = end;
  }

  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    WorkflowQueryResult workflowQueryResult = (WorkflowQueryResult) o;
    return Objects.equals(this.id, workflowQueryResult.id)
        && Objects.equals(this.name, workflowQueryResult.name)
        && Objects.equals(this.status, workflowQueryResult.status)
        && Objects.equals(this.submission, workflowQueryResult.submission)
        && Objects.equals(this.start, workflowQueryResult.start)
        && Objects.equals(this.end, workflowQueryResult.end);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, name, status, submission, start, end);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class WorkflowQueryResult {\n");

    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    submission: ").append(toIndentedString(submission)).append("\n");
    sb.append("    start: ").append(toIndentedString(start)).append("\n");
    sb.append("    end: ").append(toIndentedString(end)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
