name: Maven Package

on: ["release", "push", "pull_request"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: 17
        distribution: adopt
    - name: Install NodeJS
      uses: actions/setup-node@v4
      with:
        node-version: 16
    - name: Install TypeScript Compiler
      run: npm install -g typescript@3.9.9
    - name: Setup Repo credentials
      uses: s4u/maven-settings-action@v3.0.0
    - name: Build Shesmu with Maven
      run: mvn -B package --file pom.xml
    - name: Build Shesmu JavaDoc with Maven
      run: 'mvn javadoc:javadoc -pl shesmu-pluginapi --file pom.xml && mv shesmu-pluginapi/target/site/apidocs docs/javadoc'
    - name: Build Jekyll Documentation
      uses: actions/jekyll-build-pages@v1
      with:
        source: docs
        verbose: true
    - name: Upload Pages artifact
      uses: actions/upload-pages-artifact@v3
    - name: Build and Push Docker images
      if: ${{ github.event_name == 'release' }}
      uses: docker/build-push-action@v1.1.0
      with:
        repository: oicr-gsi/shesmu
        tags: latest
        tag_with_ref: true
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      pages: write
    steps:
    - name: Upload Pages artifact
      if: ${{ github.event_name == 'release' }}
      uses: actions/deploy-pages@v4

