name: Maven Package

on:
  release:
    types: [created]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v1
      with:
        java-version: 17
        server-id: github
    - name: Install NodeJS
      uses: actions/setup-node@v1
      with:
        node-version: 16
    - name: Install TypeScript Compiler
      run: npm install -g typescript@3.9.9
    - name: Compile Shesmu Server UI with TypeScript Compiler
      run: tsc -p shesmu-server-ui
    - name: Setup Repo credentials
      uses: s4u/maven-settings-action@v2.4.0
    - name: Build Shesmu with Maven
      run: mvn -B package --file pom.xml
    - name: Build and push Docker images
      uses: docker/build-push-action@v1.1.0
      with:
        repository: oicrgsi/shesmu
        tags: latest
        tag_with_ref: true
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
